# Simple Netlify configuration file
[build]
  publish = "dist"
  command = "pnpm install && pnpm run build"

[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-frozen-lockfile"