[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  # This tells Netlify to use .env.local during build
  NODE_ENV = "production"

# This section ensures Vite environment variables work correctly
[context.production.environment]
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"