[build]
  command = "npx pnpm install --no-frozen-lockfile && npx pnpm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--no-frozen-lockfile"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200